sources:
  - name: Hashavshevet
    handler:
      jsonSchema:
        baseUrl: "https://${WIZ_URL}/"
        operationHeaders:
          Authorization: "Bearer ${WIZ_AUTH_TOKEN}"
          host: "${WIZ_URL}"
          Content-Type: application/x-www-form-urlencoded
          Accept: application/json
        operations:
          - type: Mutation
            field: importBankPage
            path: /BankPagesApi/importBankPage
            method: POST
            requestSchema: ./json-schemas/importBankPageRequest.json
            responseSchema: ./json-schemas/importBankPageResponse.json
          - type: Query
            field: getCompanies
            path: /CompanyListToTokenApi/TokenCompanies
            method: POST
            responseSchema: ./json-schemas/getCompaniesResponse.json
          - type: Mutation
            field: newBatch
            path: /jtransApi/newBatch
            method: POST
            responseSchema: ./json-schemas/newBatchResponse.json
          - type: Query
            field: napi
            path: /api/napi
            method: POST
            responseSchema: ./json-schemas/napiResponse.json 
          - type: Query
            field: getBankPageRecords
            path: /ExportDataApi/exportData
            method: POST
            requestSchema: ./json-schemas/getBankPageRecordsRequest.json
            responseSchema: ./json-schemas/getBankPageRecordsResponse.json
          - type: Query
            field: getAllRecords
            path: /ExportDataApi/exportData
            method: POST
            requestSchema: ./json-schemas/getAllRecordsRequest.json
            responseSchema: ./json-schemas/getAllRecordsResponse.json
    transform:
      - resolversComposition:
        - resolver: Query.getBankPageRecords
          composer: ./src/resolvers/getBankPageRecordsResolver
        # - resolver: Query.getAllRecords
        #   composer: ./src/resolvers/getAllRecordsResolver
serve:
  browser: false
  exampleQuery: ./example-queries/*.graphql
