sources:
  - name: Hashavshevet
    handler:
      jsonSchema:
        baseUrl: "https://${WIZ_URL}"
        operationHeaders:
          Authorization: "Bearer ${WIZ_AUTH_TOKEN}"
          host: "${WIZ_URL}"
          content-type: "application/json"

        errorMessageField: status
        
        operations:
          - type: Mutation
            field: importBankPage
            path: /BankPagesApi/importBankPage
            method: POST
            requestSchema: ./json-schemas/importBankPageRequest.json
            responseSchema: ./json-schemas/importBankPageResponse.json
          - type: Query
            field: getCompanies
            path: /CompanyListToTokenApi/TokenCompanies
            method: POST
            responseSchema: ./json-schemas/getCompaniesResponse.json
          - type: Mutation
            field: newBatch
            path: /jtransApi/newBatch
            method: POST
            responseSchema: ./json-schemas/newBatchResponse.json
          - type: Query
            field: napi
            path: /api/napi
            method: POST
            responseSchema: ./json-schemas/napiResponse.json            
