sources:
  - name: Hashavshevet
    handler:
      jsonSchema:
        baseUrl: "https://${WIZ_URL}/"
        operationHeaders:
          Authorization: "Bearer ${WIZ_AUTH_TOKEN}"
          host: "${WIZ_URL}"
          Content-Type: application/x-www-form-urlencoded
          Accept: application/json
        operations:
          - type: Query
            field: get
            path: /api/napi
            method: POST
            responseSchema: ./json-schemas/napiResponse.json
          - type: Query
            field: getCompanies
            path: /CompanyListToTokenApi/TokenCompanies
            method: POST
            responseSchema: ./json-schemas/getCompaniesResponse.json

          - type: Query
            field: getRecords
            path: /ExportDataApi/exportData
            method: POST
            responseSchema: ./json-schemas/getRecordsResponse.json

          - type: Query
            field: getTransactions
            path: /ExportDataApi/exportData
            method: POST
            responseSchema: ./json-schemas/getTransactionsResponse.json
          # addTransactionsToBatch
            
          - type: Mutation
            field: newBatch
            path: /jtransApi/newBatch
            method: POST
            responseSchema: ./json-schemas/newBatchResponse.json
          # getBatche
          # checkBatch
          # issueBatch

          # importIndexRecords
          # deleteIndexRecords
          # getAccounts

          - type: Query
            field: getBankPageRecords
            path: /ExportDataApi/exportData
            method: POST
            requestSchema: ./json-schemas/getBankPageRecordsRequest.json
            responseSchema: ./json-schemas/getBankPageRecordsResponse.json
          - type: Mutation
            field: importBankPage
            path: /BankPagesApi/importBankPage
            method: POST
            requestSchema: ./json-schemas/importBankPageRequest.json
            responseSchema: ./json-schemas/importBankPageResponse.json

            # createDocument
            # showDocument
            # delDocument
            # issueDoc

            # crmActivities
            # crmActivitiesTest

            
    transforms:
      - resolversComposition:
          mode: bare
          compositions:
            - resolver: Query.getRecords
              composer: ./src/resolvers/getRecordsResolver
            - resolver: Query.getTransactions
              composer: ./src/resolvers/getTransactionsResolver
            - resolver: Query.getBatches
              composer: ./src/resolvers/getBatchesResolver
            - resolver: Query.getAccounts
              composer: ./src/resolvers/getAccountsResolver
            - resolver: Query.getBankPageRecords
              composer: ./src/resolvers/getBankPageRecordsResolver
serve:
  browser: false
  exampleQuery: ./example-queries/*.graphql
